# Generated by Django 2.2.4 on 2021-07-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='designation',
            field=models.CharField(default='s', max_length=1),
            preserve_default=False,
        ),
    ]
