# Generated by Django 2.2.4 on 2021-07-22 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_user_profile_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='designation',
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='uploads/resume/')),
                ('degree', models.FileField(upload_to='uploads/degree/')),
                ('verify', models.FileField(upload_to='uploads/verify/')),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
